;혼다 CMD 설정파일.
;가고일의 것+_+

;-| 초필살기 |--------------------------------------------------------

[Command]
name = "onimusou1"
command = ~D, DF, F, D, DF, F, x
time = 30

[Command]
name = "onimusou2"
command = ~D, DF, F, D, DF, F, y
time = 30

[Command]
name = "onimusou3"
command = ~D, DF, F, D, DF, F, z
time = 30

[Command]
name = "hoojioroshi1"
command = ~D, DF, F, D, DF, F, a
time = 30

[Command]
name = "hoojioroshi2"
command = ~D, DF, F, D, DF, F, b
time = 30

[Command]
name = "hoojioroshi3"
command = ~D, DF, F, D, DF, F, c
time = 30

[Command]
name = "orochikudaki"
command = ~D, DB, B, D, DB, B, x
time = 30

[Command]
name = "orochikudaki"
command = ~D, DB, B, D, DB, B, y
time = 30

[Command]
name = "orochikudaki"
command = ~D, DB, B, D, DB, B, z
time = 30

[Command]
name = "shungokujyou"
command = ~x, x, F, a, z
time = 35

[Command]
name = "g-groove"
command = ~D, DB, B, D, DB, B, s
time = 30

;-| 필살기 |------------------------------------------------------
[Command]
name = "super1"
command = ~30$B, F, x
time = 20

[Command]
name = "super2"
command = ~30$B, F, y
time = 20

[Command]
name = "super3"
command = ~30$B, F, z
time = 20

[Command]
name = "hyakkan1"
command = ~F, D, F, a
time = 20

[Command]
name = "hyakkan2"
command = ~F, D, F, b
time = 20

[Command]
name = "hyakkan3"
command = ~F, D, F, c
time = 20

[Command]
name = "nage1"
command = ~F, DF, D, DB, B, F, x
time = 30

[Command]
name = "nage2"
command = ~F, DF, D, DB, B, F, y
time = 30

[Command]
name = "nage3"
command = ~F, DF, D, DB, B, F, z
time = 30

[Command]
name = "hyakkuretsu1"
command = x, x, x
time = 20

[Command]
name = "hyakkuretsu2"
command = y, y, y
time = 20

[Command]
name = "hyakkuretsu3"
command = z, z, z
time = 20

[Command]
name = "asura-f1"
command = F, D, DF, x+y
time = 20

[Command]
name = "asura-f1"
command = F, D, DF, x+z
time = 20

[Command]
name = "asura-f1"
command = F, D, DF, y+z
time = 20

[Command]
name = "asura-f2"
command = F, D, DF, a+b
time = 20

[Command]
name = "asura-f2"
command = F, D, DF, a+c
time = 20

[Command]
name = "asura-f2"
command = F, D, DF, b+c
time = 20

[Command]
name = "asura-b1"
command = B, D, DB, x+y
time = 20

[Command]
name = "asura-b1"
command = B, D, DB, x+z
time = 20

[Command]
name = "asura-b1"
command = B, D, DB, y+z
time = 20

[Command]
name = "asura-b2"
command = B, D, DB, a+b
time = 20

[Command]
name = "asura-b2"
command = B, D, DB, a+c
time = 20

[Command]
name = "asura-b2"
command = B, D, DB, b+c
time = 20

[Command]
name = "mesatzgou1"
command = F, D, DF, x
time = 20

[Command]
name = "mesatzgou2"
command = F, D, DF, y
time = 20

[Command]
name = "mesatzgou3"
command = F, D, DF, z
time = 20

[Command]
name = "zanku1"
command = D, DF, F, x
time = 20

[Command]
name = "zanku2"
command = D, DF, F, y
time = 20

[Command]
name = "zanku3"
command = D, DF, F, z
time = 20

[Command]
name = "groggyrecover"
command = F,B
time = 20

;-| Double Tap |-----------------------------------------------------------
[Command]
name = "FF"     ;Required (do not remove)
command = F, F
time = 10

[Command]
name = "BB"     ;Required (do not remove)
command = B, B
time = 10

;-| 2/3 Button Combination |-----------------------------------------------
[Command]
name = "recovery"
command = x+y
time = 1

[Command]
name = "throw1"
command = x+y
time = 1

[Command]
name = "throw1"
command = y+z
time = 1

[Command]
name = "throw1"
command = x+z
time = 1

[Command]
name = "throw2"
command = a+b
time = 1

[Command]
name = "throw2"
command = b+c
time = 1

[Command]
name = "throw2"
command = a+c
time = 1

[Command]
name = "zero"
command = a+x
time = 1

[Command]
name = "zero"
command = b+y
time = 1

[Command]
name = "zero"
command = c+z
time = 1

;-| Dir + Button |---------------------------------------------------------
[Command]
name = "down_a"
command = /$D,a
time = 1

[Command]
name = "down_b"
command = /$D,b
time = 1

;-| Single Button |---------------------------------------------------------
[Command]
name = "a"
command = a
time = 1

[Command]
name = "b"
command = b
time = 1

[Command]
name = "c"
command = c
time = 1

[Command]
name = "x"
command = x
time = 1

[Command]
name = "y"
command = y
time = 1

[Command]
name = "z"
command = z
time = 1

[Command]
name = "start"
command = s
time = 1

[Command]
name = "hit"
command = x
time = 1

[Command]
name = "hit"
command = y
time = 1

[Command]
name = "hit"
command = z
time = 1

[Command]
name = "hit"
command = a
time = 1

[Command]
name = "hit"
command = b
time = 1

[Command]
name = "hit"
command = c
time = 1

[Command]
name = "hit"
command = F
time = 1

[Command]
name = "hit"
command = B
time = 1

;-| Hold Dir |--------------------------------------------------------------
[Command]
name = "holdfwd";Required (do not remove)
command = /$F
time = 1

[Command]
name = "holdback";Required (do not remove)
command = /$B
time = 1

[Command]
name = "holdup" ;Required (do not remove)
command = /$U
time = 1

[Command]
name = "holddown";Required (do not remove)
command = /$D
time = 1

;---------------------------------------------------------------------------
; Don't remove the following line. It's required by the CMD standard.
[Statedef -1]
;===========================================================================
;순옥장
[State -1, ShunGokuJyou]
type = ChangeState
value = 3020
triggerall = Var(9) = 1
triggerall = power >= 3000
triggerall = command = "shungokujyou"
triggerall = stateno != [1000,3999]
trigger1 = statetype = S
trigger2 = stateno = [200,404]
trigger2 = movecontact = 1
;---------------------------------------------------------------------------
;대사 죽이기
[State -1, OrochiKudaki]
type = ChangeState
value = 3030
triggerall = Var(9) = 0
triggerall = power >= 3000
triggerall = command = "orochikudaki"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = [200,404]
trigger2 = movecontact = 1
;---------------------------------------------------------------------------
;후지오로시
[State -1, HoojiOroshi]
type = ChangeState
value = 3010
triggerall = Var(9) = 0
triggerall = power >= 1000
triggerall = command = "hoojioroshi1" || command = "hoojioroshi2" || command = "hoojioroshi3" 
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = [200,404]
trigger2 = movecontact = 1
;---------------------------------------------------------------------------
;귀무쌍(진공박치기)
[State -1, OniMusou]
type = ChangeState
value = ifelse (Var(9) = 0, 3000, 3005)
triggerall = power >= 1000
triggerall = command = "onimusou1" || command = "onimusou2" || command = "onimusou3" 
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = [200,404]
trigger2 = movecontact = 1
;---------------------------------------------------------------------------
;G그루브 발동
[State -1, G-groove Start]
type = ChangeState
value = ifelse (Var(9) = 0, 850, 851)
triggerall = power >= ifelse (Var(9) = 0, 1000, 0)
triggerall = command = "g-groove"
trigger1 = statetype = S
trigger1 = ctrl 
;---------------------------------------------------------------------------
;아수라 섬공 전방
[State - 1, AsuraSengoku]
type = ChangeState
value  = 900
triggerall = Var(9) = 1
triggerall = command = "asura-f1" || command = "asura-f2" 
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = [200,404]
trigger2 = movecontact = 1

;---------------------------------------------------------------------------
;아수라 섬공 후방
[State - 1, AsuraSengoku]
type = ChangeState
value  = 902
triggerall = Var(9) = 1
triggerall = command = "asura-b1" || command = "asura-b2" 
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = [200,404]
trigger2 = movecontact = 1

;---------------------------------------------------------------------------
;햐키고우잔
[State - 1, HyakkiShuu]
type = ChangeState
value  = 1020
triggerall = Var(9) = 1
triggerall = command = "hyakkan1" || command = "hyakkan2" || command = "hyakkan3" 
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = [200,404]
trigger2 = movecontact = 1

;---------------------------------------------------------------------------
;멸살호 박치기
[State - 1, metsatzGou]
type = ChangeState
value  = 1050
triggerall = Var(9) = 1
triggerall = command = "mesatzgou1" || command = "mesatzgou2" || command = "mesatzgou3" 
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = [200,404]
trigger2 = movecontact = 1

;---------------------------------------------------------------------------
;햐키고우사이
[State -1, HyakkiGouSai]
type = ChangeState
value = 1026
triggerall = time >= 12
triggerall = p2bodydist x <= 0
triggerall = p2bodydist x >= -35
trigger1 = command = "x" || command = "y" || command = "z"
trigger1 = command = "holdfwd" || command = "holdback"
trigger1 = stateno = 1020

;-----------------------------------------------------------------------------
;햐키고우츠이
[State -1, HyakkiGouTsui]
type = ChangeState
value = 1032
triggerall = time >= 12
triggerall = p2bodydist x < 8
trigger1 = command = "a" || command = "b" || command = "c"
trigger1 = command = "holdfwd" || command = "holdback"
trigger1 = stateno = 1020

;----------------------------------------------------------------------------
;햐키고쇼우
[State -1, HyakkiGouShou]
type = ChangeState
value = 1022
triggerall = time >= 12
trigger1 = command = "x" || command = "y" || command = "z" 
trigger1 = stateno = 1020

;---------------------------------------------------------------------------
;햐키고우센
[State -1, HyakkiGouSen]
type = ChangeState
value = 1024
triggerall = time >= 12
trigger1 = command = "a" || command = "b" || command = "c"
trigger1 = stateno = 1020

;----------------------------------------------------------------------------
;천마공인각
[State -1, TenmaKujinKyaku]
type = ChangeState
value = 1040
triggerall = Var(9) = 1
triggerall = command = "holddown"
triggerall = command = "a" || command = "b" || command = "c"
trigger1 = statetype = A
trigger1 = ctrl = 1
trigger2 = stateno = [600,700]
trigger2 = movecontact = 1

;----------------------------------------------------------------------------
;참공 박치기
[State -1, ZanKu Zutski]
type = ChangeState
value = 1055
triggerall = Var(9) = 1
triggerall = command = "zanku1" || command = "zanku2" || command = "zanku3"
trigger1 = statetype = A
trigger1 = ctrl = 1
trigger2 = stateno = [600,700]
trigger2 = movecontact = 1

;----------------------------------------------------------------------------
;슈퍼박치기 약
[State -1, Super Zutsuki]
type = ChangeState
value = 1000
triggerall = command = "super1"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 403
trigger2 = movecontact
trigger3 = Var(9) = 1
trigger3 = stateno = 200
trigger3 = movecontact
trigger4 = Var(9) = 1
trigger4 = stateno = 201
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 202
trigger5 = AnimElem = 2
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 203
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 204
trigger7 = movecontact
trigger8 = Var(9) = 1
trigger8 = stateno = 205
trigger8 = AnimElem = 3
trigger8 = movecontact
trigger9 = Var(9) = 1
trigger9 = stateno = 400
trigger9 = movecontact
trigger10 = Var(9) = 1
trigger10 = stateno = 401
trigger10 = movecontact
trigger11 = Var(9) = 1
trigger11 = stateno = 402
trigger11 = AnimElem = 2
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;슈퍼박치기 중
[State -1, Super Zutsuki]
type = ChangeState
value = 1001
triggerall = command = "super2"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 403
trigger2 = movecontact
trigger3 = Var(9) = 1
trigger3 = stateno = 200
trigger3 = movecontact
trigger4 = Var(9) = 1
trigger4 = stateno = 201
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 202
trigger5 = AnimElem = 2
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 203
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 204
trigger7 = movecontact
trigger8 = Var(9) = 1
trigger8 = stateno = 205
trigger8 = AnimElem = 3
trigger8 = movecontact
trigger9 = Var(9) = 1
trigger9 = stateno = 400
trigger9 = movecontact
trigger10 = Var(9) = 1
trigger10 = stateno = 401
trigger10 = movecontact
trigger11 = Var(9) = 1
trigger11 = stateno = 402
trigger11 = AnimElem = 2
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;슈퍼박치기 강
[State -1, Super Zutsuki]
type = ChangeState
value = 1002
triggerall = command = "super3"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 403
trigger2 = movecontact
trigger3 = Var(9) = 1
trigger3 = stateno = 200
trigger3 = movecontact
trigger4 = Var(9) = 1
trigger4 = stateno = 201
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 202
trigger5 = AnimElem = 2
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 203
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 204
trigger7 = movecontact
trigger8 = Var(9) = 1
trigger8 = stateno = 205
trigger8 = AnimElem = 3
trigger8 = movecontact
trigger9 = Var(9) = 1
trigger9 = stateno = 400
trigger9 = movecontact
trigger10 = Var(9) = 1
trigger10 = stateno = 401
trigger10 = movecontact
trigger11 = Var(9) = 1
trigger11 = stateno = 402
trigger11 = AnimElem = 2
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;슈퍼 백관락 떨어뜨리기 약
[State -1, Super hyakkanOtoshi]
type = ChangeState
value = 1005
triggerall = var(9) = 0
triggerall = command = "hyakkan1"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = Var(9) = 1
trigger2 = stateno = 200
trigger2 = movecontact
trigger3 = Var(9) = 1
trigger3 = stateno = 201
trigger3 = movecontact
trigger4 = Var(9) = 1
trigger4 = stateno = 202
trigger4 = AnimElem = 2
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 203
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 204
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 205
trigger7 = AnimElem = 3
trigger7 = movecontact
trigger8 = Var(9) = 1
trigger8 = stateno = 400
trigger8 = movecontact
trigger9 = Var(9) = 1
trigger9 = stateno = 401
trigger9 = movecontact
trigger10 = Var(9) = 1
trigger10 = stateno = 402
trigger10 = AnimElem = 2
trigger10 = movecontact
trigger11 = Var(9) = 1
trigger11 = stateno = 403
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;슈퍼 백관락 떨어뜨리기 중
[State -1, Super hyakkanOtoshi]
type = ChangeState
value = 1006
triggerall = var(9) = 0
triggerall = command = "hyakkan2"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = Var(9) = 1
trigger2 = stateno = 200
trigger2 = movecontact
trigger3 = Var(9) = 1
trigger3 = stateno = 201
trigger3 = movecontact
trigger4 = Var(9) = 1
trigger4 = stateno = 202
trigger4 = AnimElem = 2
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 203
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 204
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 205
trigger7 = AnimElem = 3
trigger7 = movecontact
trigger8 = Var(9) = 1
trigger8 = stateno = 400
trigger8 = movecontact
trigger9 = Var(9) = 1
trigger9 = stateno = 401
trigger9 = movecontact
trigger10 = Var(9) = 1
trigger10 = stateno = 402
trigger10 = AnimElem = 2
trigger10 = movecontact
trigger11 = Var(9) = 1
trigger11 = stateno = 403
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;슈퍼 백관락 떨어뜨리기 강
[State -1, Super hyakkanOtoshi]
type = ChangeState
value = 1007
triggerall = var(9) = 0
triggerall = command = "hyakkan3"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = Var(9) = 1
trigger2 = stateno = 200
trigger2 = movecontact
trigger3 = Var(9) = 1
trigger3 = stateno = 201
trigger3 = movecontact
trigger4 = Var(9) = 1
trigger4 = stateno = 202
trigger4 = AnimElem = 2
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 203
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 204
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 205
trigger7 = AnimElem = 3
trigger7 = movecontact
trigger8 = Var(9) = 1
trigger8 = stateno = 400
trigger8 = movecontact
trigger9 = Var(9) = 1
trigger9 = stateno = 401
trigger9 = movecontact
trigger10 = Var(9) = 1
trigger10 = stateno = 402
trigger10 = AnimElem = 2
trigger10 = movecontact
trigger11 = Var(9) = 1
trigger11 = stateno = 403
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;백열장 약
[State -1, hyakkuretsujou]
type = ChangeState
value = 1010
triggerall = command = "hyakkuretsu1"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200
trigger2 = movecontact
trigger3 = stateno = 201
trigger3 = movecontact
trigger4 = stateno = 202
trigger4 = AnimElem = 2
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 203
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 204
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 205
trigger7 = AnimElem = 3
trigger7 = movecontact
trigger8 = stateno = 400
trigger8 = movecontact
trigger9 = stateno = 401
trigger9 = movecontact
trigger10 = stateno = 402
trigger10 = AnimElem = 2
trigger10 = movecontact
trigger11 = Var(9) = 1
trigger11 = stateno = 403
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;백열장 중
[State -1, hyakkuretsujou]
type = ChangeState
value = 1011
triggerall = command = "hyakkuretsu2"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200
trigger2 = movecontact
trigger3 = stateno = 201
trigger3 = movecontact
trigger4 = stateno = 202
trigger4 = AnimElem = 2
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 203
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 204
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 205
trigger7 = AnimElem = 3
trigger7 = movecontact
trigger8 = stateno = 400
trigger8 = movecontact
trigger9 = stateno = 401
trigger9 = movecontact
trigger10 = stateno = 402
trigger10 = AnimElem = 2
trigger10 = movecontact
trigger11 = Var(9) = 1
trigger11 = stateno = 403
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact 
;---------------------------------------------------------------------------
;백열장 강
[State -1, hyakkuretsujou]
type = ChangeState
value = 1012
triggerall = command = "hyakkuretsu3"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200
trigger2 = movecontact
trigger3 = stateno = 201
trigger3 = movecontact
trigger4 = stateno = 202
trigger4 = AnimElem = 2
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 203
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 204
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 205
trigger7 = AnimElem = 3
trigger7 = movecontact
trigger8 = stateno = 400
trigger8 = movecontact
trigger9 = stateno = 401
trigger9 = movecontact
trigger10 = stateno = 402
trigger10 = AnimElem = 2
trigger10 = movecontact
trigger11 = Var(9) = 1
trigger11 = stateno = 403
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact 
;---------------------------------------------------------------------------
;은행던지기 약
[State -1, Ooichou Nage]
type = ChangeState
value = 1015
triggerall = command = "nage1"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200
trigger2 = movecontact
trigger3 = stateno = 201
trigger3 = movecontact
trigger4 = stateno = 202
trigger4 = AnimElem = 2
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 203
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 204
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 205
trigger7 = AnimElem = 3
trigger7 = movecontact
trigger8 = stateno = 400
trigger8 = movecontact
trigger9 = Var(9) = 1
trigger9 = stateno = 401
trigger9 = movecontact
trigger10 = Var(9) = 1
trigger10 = stateno = 402
trigger10 = AnimElem = 2
trigger10 = movecontact
trigger11 = stateno = 403
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;은행던지기 중
[State -1, Ooichou Nage]
type = ChangeState
value = 1015
triggerall = command = "nage2"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200
trigger2 = movecontact
trigger3 = stateno = 201
trigger3 = movecontact
trigger4 = stateno = 202
trigger4 = AnimElem = 2
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 203
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 204
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 205
trigger7 = AnimElem = 3
trigger7 = movecontact
trigger8 = stateno = 400
trigger8 = movecontact
trigger9 = Var(9) = 1
trigger9 = stateno = 401
trigger9 = movecontact
trigger10 = Var(9) = 1
trigger10 = stateno = 402
trigger10 = AnimElem = 2
trigger10 = movecontact
trigger11 = stateno = 403
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;은행던지기 강
[State -1, Ooichou Nage]
type = ChangeState
value = 1015
triggerall = command = "nage3"
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = 200
trigger2 = movecontact
trigger3 = stateno = 201
trigger3 = movecontact
trigger4 = stateno = 202
trigger4 = AnimElem = 2
trigger4 = movecontact
trigger5 = Var(9) = 1
trigger5 = stateno = 203
trigger5 = movecontact
trigger6 = Var(9) = 1
trigger6 = stateno = 204
trigger6 = movecontact
trigger7 = Var(9) = 1
trigger7 = stateno = 205
trigger7 = AnimElem = 3
trigger7 = movecontact
trigger8 = stateno = 400
trigger8 = movecontact
trigger9 = Var(9) = 1
trigger9 = stateno = 401
trigger9 = movecontact
trigger10 = Var(9) = 1
trigger10 = stateno = 402
trigger10 = AnimElem = 2
trigger10 = movecontact
trigger11 = stateno = 403
trigger11 = movecontact
trigger12 = Var(9) = 1
trigger12 = stateno = 404
trigger12 = AnimElem = 2
trigger12 = movecontact
;---------------------------------------------------------------------------
;===========================================================================
;---------------------------------------------------------------------------
;전방 대시
[State -1, Run Fwd]
type = ChangeState
value = 100
trigger1 = command = "FF"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;후방 대시
[State -1, Run Back]
type = ChangeState
value = 105
trigger1 = command = "BB"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;펀치 잡기
[State -1, Punch Throw]
type = ChangeState
value = 800
triggerall = command = "throw1"
triggerall = statetype = S
triggerall = ctrl
triggerall = stateno != 100
trigger1 = command = "holdfwd"
trigger2 = command = "holdback"

;---------------------------------------------------------------------------
;킥 잡기
[State -1, Kick Throw]
type = ChangeState
value = 805
triggerall = command = "throw2"
triggerall = statetype = S
triggerall = ctrl
triggerall = stateno != 100
trigger1 = command = "holdfwd"
trigger2 = command = "holdback"

;---------------------------------------------------------------------------
;공중 잡기
[State -1, Air Throw]
type = ChangeState
value = 809
triggerall = command = "throw1"
triggerall = statetype = A
triggerall = ctrl
trigger1 = command = "holdfwd"
trigger2 = command = "holdback"

;---------------------------------------------------------------------------
;서서 약펀치
[State -1, Stand Light Punch]
type = ChangeState
value = 200
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;서서 중펀치
[State -1, Stand Medium Punch]
type = ChangeState
value = 201
triggerall = command = "y"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;서서 강펀치
[State -1, Stand Strong Punch]
type = ChangeState
value = 202
triggerall = command = "z"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;서서 약킥
[State -1, Stand Light Kick]
type = ChangeState
value = 203
triggerall = command = "a"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;서서 중킥
[State -1, Stand Medium Kick]
type = ChangeState
value = 204
triggerall = command = "b"
triggerall = command != "holdfwd"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;서서 강킥
[State -1, Standing Strong Kick]
type = ChangeState
value = 205
triggerall = command = "c"
triggerall = command != "holdfwd"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;무릎차기
[State -1, Knee Kick]
type = ChangeState
value = 300
triggerall = command = "b"
triggerall = command = "holdfwd"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;때려차기
[State -1, ....Kick]
type = ChangeState
value = 301
triggerall = command = "c"
triggerall = command = "holdfwd"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl

;---------------------------------------------------------------------------
;도발
[State -1, Taunt]
type = ChangeState
value = ifelse (Var(9) = 0, 195, 196)
triggerall = Var(11) = 0
triggerall = command = "start"
trigger1 = statetype != A
trigger1 = ctrl

;---------------------------------------------------------------------------
;하단 약펀치
[State -1, Crouching Light Punch]
type = ChangeState
value = 400
triggerall = command = "x"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;하단 중펀치
[State -1, Crouching Medium Punch]
type = ChangeState
value = 401
triggerall = command = "y"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;하단 강펀치
[State -1, Crouching Strong Punch]
type = ChangeState
value = 402
triggerall = command = "z"
triggerall = command = "holddown"
triggerall = command != "holdfwd"
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;하단 약킥
[State -1, Crouching Light Kick]
type = ChangeState
value = 403
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;하단 중킥
[State -1, Crouching Medium Kick]
type = ChangeState
value = 404
triggerall = command = "b"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;하단 강킥
[State -1, Crouching Strong Kick]
type = ChangeState
value = 405
triggerall = command = "c"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;하단 후리기
[State -1, Crouching Strong Punch2]
type = ChangeState
value = 500
triggerall = command = "z"
triggerall = command = "holddown"
triggerall = command = "holdfwd"
trigger1 = statetype = C
trigger1 = ctrl

;---------------------------------------------------------------------------
;점프 약펀치
[State -1, Jump Light Punch]
type = ChangeState
value = 600
triggerall = command = "x"
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;점프 중펀치
[State -1, Jump medium Punch]
type = ChangeState
value = 601
triggerall = command = "y"
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;점프 강펀치
[State -1, Jump Strong Punch]
type = ChangeState
value = 602
triggerall = command = "z"
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;점프 약킥
[State -1, Jump Light Kick]
type = ChangeState
value = 603
triggerall = command = "a"
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;점프 중킥
[State -1, Jump Medium Kick]
type = ChangeState
value = 604
triggerall = command = "b"
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;점프 강킥
[State -1, Jump Strong Kick]
type = ChangeState
value = 605
triggerall = command = "c"
trigger1 = statetype = A
trigger1 = ctrl

;---------------------------------------------------------------------------
;제로 카운터
[State -1, Zero Counter]
type = ChangeState
value = 818
triggerall = command = "holdfwd"
triggerall = command = "zero"
triggerall = var(4) > 0
triggerall = power >= 1000 
trigger1 = stateno = [150,153]
ignorehitpause = 1

;---------------------------------------------------------------------------
